name: Terraform Deploy

on:
  push:
    branches:
      - main
    
jobs:
  shell_command:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Ruby
      uses: actions/setup-ruby@v2
      with:
       ruby-version: 2.6.5
    - name: Show ruby version
      run: ruby -v

