name: Terraform Deploy

on:
  push:
    branches:
      - main
jobs:
  shell_command:
    runs-on: ubuntu-latest
    steps:
      - name: Setup git
        uses: actions/checkout@v2
        #with:
          #token: ${{ secrets.VOX_GITHUB_TOKEN }}
      - name: Clone repository
        run: sudo git clone https://github.com/rbenv/rbenv.git ~/.rbenv
      - name:   Install Rbenv
        run: sudo echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
             sudo echo 'eval "$(rbenv init -)"' >> ~/.bashrc
             sudo source ~/.bashrc
      - name: install ruby2.6.5
        run: rbenv install 2.6.5
      - name: install global
        run:  rbenv global 2.6.5
      - id: slack
      - name: Post to a Slack channel
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # The following message update step does not accept a channel name.
          # Setting a channel ID here for consistency is highly recommended.
          channel-id: "C04MCAU1VPE"
          payload: |
            {
              "text": "Deployment started (In Progress)",
              "attachments": [
                {
                  "pretext": "Deployment started",
                  "color": "dbab09",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                       "value": "In Progress"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
      - uses: slackapi/slack-github-action@v1.23.0
        with:
            # Unlike the step posting a new message, this step does not accept a channel name.
            # Please use a channel ID, not a name here.
          channel-id: "C04MCAU1VPE"
          update-ts: ${{ steps.slack.outputs.ts }}
          payload: |
            {
              "text": "Deployment finished (Completed)",
              "attachments": [
                 {
                  "pretext": "Deployment finished",
                  "color": "28a745",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "Completed"
                    }
                  ]
                }
              ]
            }
        env: 
         SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}  
