name: Terraform Deploy

on:
  push:
    branches:
      - main
jobs:
  shell_command:
    runs-on: ubuntu-latest
    steps:
      - name: Setup git
        uses: actions/checkout@v2
        #with:
          #token: ${{ secrets.VOX_GITHUB_TOKEN }}
      - name: Clone repository
        run: sudo apt install git curl autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm6 libgdbm-dev libdb-dev
      - name:   Install Rbenv
        run: curl -fsSL https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer | bash
      - name: You echo
        run: echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
             echo 'eval "$(rbenv init -)"' >> ~/.bashrc
             source ~/.bashrc
      - name: install ruby2.6.5
        run : rbenv install 2.6.5
      - name: install global
        run: rbenv global 2.6.5
