name: Terraform Deploy

on:
  push:
    branches:
      - main
jobs:
  shell_command:
    runs-on: ubuntu-latest
    steps:
      - name: Setup git
        uses: actions/checkout@v2
        #with:
          #token: ${{ secrets.VOX_GITHUB_TOKEN }}
      - name: Clone repository
        run: sudo git clone https://github.com/rbenv/rbenv.git ~/.rbenv
      - name:   Install Rbenv
        run: sudo echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
             sudo echo 'eval "$(rbenv init -)"' >> ~/.bashrc
             sudo source ~/.bashrc
      - name: install ruby2.6.5
        run: rbenv install 2.6.5
      - name: install global
        run:  rbenv global 2.6.5
      - name: slack-send
        uses: slackapi/slack-github-action@v1.23.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          #SLACK_CHANNEL: C04MCAU1VPE
        with:
           channel-id: "C04MCAU1VPE"
           status: ${{ job.status }}
           steps: ${{ toJson(steps) }}
           channel: '#git-hub-action-cicd'
        if: always()   
