name: Terraform Deploy

on:
  push:
    branches:
      - main
jobs:
  shell_command:
    runs-on: ubuntu-latest
    steps:
      - name: Setup git
        uses: actions/checkout@v2
        #with:
          #token: ${{ secrets.VOX_GITHUB_TOKEN }}
      - name: Clone repository
        run: sudo git clone https://github.com/rbenv/rbenv.git ~/.rbenv
      - name:   Install Rbenv
        run: echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
             echo 'eval "$(rbenv init -)"' >> ~/.bashrc
             source ~/.bashrc
      - name: install ruby2.6.5
        run : sudo apt-get install -y rbenv install 2.6.5
      - name: install global
        run: sudo apt-get install -y rbenv global 2.6.5
